function vertexValues = vertexValuesFromRegions(regionLabels, regionValues)
% Returns a vector of per-vertex values expanded from per-region values
% 
% vertexValues = vertexValuesFromRegions(regionLabels, regionValues)
%
% Required:
%   regionLabels:   a regionLabels variable, e.g. as generated by abcd.loadAal78()
%   regionValues:   vector of values corresponding to each region

assert(isvector(regionValues), 'regionValues must be a vector');
assert(numel(regionValues) <= numel(regionLabels.regions), 'regionValues has more values than the number of regions!');

defaultValue = 0;

vertexValues = repmat(defaultValue, 1,numel(regionLabels.idByVertex));

for iRgn = 1:numel(regionValues)
    vertexValues(regionLabels.idByVertex == iRgn) = regionValues(iRgn);
end

end